### PR TITLE
Correcting README

### PR DESCRIPTION
**Pull request by sciolizer**
Fixing the `<groupId>` and updating the versions.

### CODE REVIEW

**Comment by boynton** [comment]
I think we should leave the package as rdl, not ardielle.

**Comment by sciolizer** [comment]
Isn't that what I did? To what line are you referring?

**Comment by helix-lee** [comment]
Sorry, my bad. Yes, the docs now match reality, which is good.

**Comment by helix-lee** [comment]
👍

**Comment by boynton** [comment]
Never mind, I misread. 👍

**Pull request merged**
